#!/bin/bash

mainURL="$1"

function repositoryClone(){
  URL=${mainURL%.git}
  TAR='/tarball/master'
  wget -O name.tar.gz $URL$TAR
  tar -xvf name.tar.gz
  rm -rf name.tar.gz
}

function helpF(){
  printf '
  [INFORMATION]

    This script acts like git. Instead of using <git clone URL>, it gets the actual TAR.GZ file and extract, further removing the TAR.GZ file.
    Useful for systems that use different kernel, such as Android.

  [USAGE]

    bash lessgit URL

  [COMMANDS]

    -h: prints this option.
    -v: prints the version of the script.

'
}

function versionF(){
  printf '  lessgit 1.1 - KanuX-14 | 09/17/2020 ~ 1:25AM'
}

while getopts ':hv' opt; do
  case $opt in
    h) helpF
    ;;
    v) versionF
    ;;
    *) printf 'This input does not exists!'
    ;;
  esac
done

if [ "$mainURL" != "" ]; then
  repositoryClone
else
  helpF
fi
